server:
  port: 8080
  servlet:
    session:
      timeout: 1
spring:
  datasource:
    username: root
    password: 970226
    url: jdbc:mysql://localhost:3306/agile-boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
  flyway:
    locations:
      - classpath:db/migration
    #如果数据库不是空表，需要设置为true，否则启动报错
    baseline-on-migrate: true
    encoding: UTF-8
    #校验
    validate-on-migrate: true
    clean-disabled: false
  #rabbitmq:
    #host: 127.0.0.1
    #port: 5672
    #username: guest
    #password: guest
mybatis:
  mapper-locations: classpath:modules/*/*.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#jwt
jwt:
  header: token
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: cuAihCz53DZRjZwbsGcZJ2Ai6At+T142uphtJMsk7iQ=cuAihCz53DZRjZwbsGcZJ2Ai6At+T142uphtJMsk7iQ=
  # 令牌过期时间 此处单位/毫秒
  token-validity-in-seconds: 600000

