server:
  port: 8080
  servlet:
    session:
      timeout: 1
spring:
  datasource:
    username: root
    password: 970226
    url: jdbc:mysql://localhost:3306/agile-boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  aop:
    auto: true
  flyway:
    locations:
      - classpath:db/migration
    #如果数据库不是空表，需要设置为true，否则启动报错
    baseline-on-migrate: true
    encoding: UTF-8
    #校验
    validate-on-migrate: true
    clean-disabled: false
  #rabbitmq:
    #host: 127.0.0.1
    #port: 5672
    #username: guest
    #password: guest

mybatis-plus:
  mapper-locations: classpath:modules/*/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: is_deleted
    #configuration:
    # 打印执行的SQL语句及返回的数据
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
