server:
  port: 8080
spring:
  datasource:
    username: root
    password: 970226
    url: jdbc:mysql://localhost:3306/agile-boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
  #type: com.alibaba.druid.pool.DruidDataSource
  #activiti:
    #表示启动时检查数据库表，不存在则创建
    #database-schema: true
    #表示哪种情况下使用历史表，这里配置为full表示全部记录历史，方便绘制流程图
    #history-level: full
    #true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表
    #db-history-used: true
    #校验流程文件，默认校验resources/processes下的流程文件
    #check-process-definitions: false
mybatis:
  mapper-locations: classpath:modules/*/*.xml

